name: Run Pytest

on: 
  [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Display Matrix Version
        run: python -c "import sys; import platform; print(f'{sys.version=}, {platform.system()=}'')"
    
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          channels: dwr-cvm,cadwr-dms,defaults,conda-forge
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true
      
      - name: Test with Pytest
        run: python -m pytest tests